package:
    name: sf_bsread_writer
    version: 0.0.1

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bsread

build:
  entry_points:
    - sf_bsread_writer = sf_bsread_writer.start_server:main

about:
    home:
