package:
    name: sf_bsread_writer
    version: 1.1.1

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bsread >=1.1.0
        - bottle
        - requests

build:
  entry_points:
    - sf_bsread_writer = sf_bsread_writer.writer:run
    - sf_bsread_buffer = sf_bsread_writer.buffer:run

about:
    home: https://github.com/paulscherrerinstitute/sf_bsread_writer
