package:
    name: sf_bsread_writer
    version: 0.0.2

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bsread >=1.1.0
        - requests

build:
  entry_points:
    - sf_bsread_writer = sf_bsread_writer.start_server:run
    - sf_bsread_buffer = sf_bsread_writer.start_server:run

about:
    home:
